spring:
  application:
    name: registration-service


server:
  port: ${PORT:8082}
  servlet:
    context-path: /api/v1/

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka.cedesistemas.local:8761/eureka/

info:
  app:
    name: ${spring.application.name}
    description: e-commerce registration service
    port: ${server.port}
    version: 1.0.0