spring:
  application:
    name: registration-service
  data:
    mongodb:
      authentication-database: admin
      database: tech-ecommerce
      port: 27017
      host: localhost
  profiles:
    active: sanbox

server:
  port: 7080
  servlet:
    context-path: /api/v1/



info:
  app:
    name: ${spring.application.name}
    description: e-commerce registration service
    port: ${server.port}
    version: 1.0.0
