spring:
  application:
    name: registration-service
  data:
    mongodb:
      authentication-database: admin
      database: tech-ecommerce
      port: 27017
      host: mongodb.cedesistemas.local
  zipkin:
    base-url: http://jaeger.cedesistemas.local:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: rabbitmq.cedesistemas.local
    port: 5672
    username: guest
    password: guest

server:
  port: ${PORT:8083}
  servlet:
    context-path: /api/v1/

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC

management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: ${spring.application.name}
    description: e-commerce registration service
    port: ${server.port}
    version: 1.0.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eureka.cedesistemas.local:8761/eureka/