spring:
  application:
    name: shipping-service

server:
  port: ${PORT:8086}
  servlet:
    context-path: /api/v1/

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC