spring:
  application:
    name: payment-service
  data:
    mongodb:
      authentication-database: admin
      database: tech-ecommerce
      port: 27017
      host: mongodb.cedesistemas.local
  zipkin:
    base-url: http://jaeger.cedesistemas.local:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: rabbitmq.cedesistemas.local
    port: 5672
    username: guest
    password: guest
    virtual-host:

