spring:
  data:
    mongodb:
      authentication-database: admin
      database: tech-ecommerce-test
      port: 27017
      host: mongodb.cedesistemas.local

server:
  servlet:
    context-path: /api/v1/